name: Build Image wth buildx

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    services:
      docker:
        name: docker-dind
        image: docker:27-dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro

    steps:
      - uses: actions/checkout@v4

      - run: |
          docker cp $(pwd) docker-dind:/build
          docker exec -i docker-dind sh -c "cd /build && ./build.sh"
