name: Build Image wth buildx

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - run: |
          docker run -d --name some-docker -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/build --privileged docker:27-dind
          docker exec -i some-docker sh -c "cd /build && ls && ./build.sh"
          docker rm -f some-docker