name: Build Image wth buildx

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - run: |
          docker info
          docker run -d --name some-docker -v $(pwd):/build --privileged -e DOCKER_OPTS="--storage-driver=fuse-overlayfs" --entrypoint dockerd docker:27-dind --host=unix:///var/run/docker.sock
          docker exec -i some-docker sh -c "cd /build && ./build.sh"

      - run: |
          docker logs some-docker
          docker rm -f some-docker
        if: always()